name: Auto add dev tickets to project board

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check labels and add to project
        if: |
          !contains(github.event.issue.labels.*.name, 'Requests') &&
          !contains(github.event.issue.labels.*.name, 'Bug Reports')
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/AllenCell/projects/7
          content-id: ${{ github.event.issue.node_id }}
          column-name: Backlog