# Publishes to PyPI when a commit tagged with v** is pushed to main
name: Publish to PyPI 

on:
  push:
    branches:
      - main
    paths:
      - version.toml

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
    
      - name: Build Package
        run: |
          python -m build
    
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
