name: Create or increment a hotfix/post tag on a branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Hotfix branch"
        required: true
        type: string

jobs:
  tag:
    name: Tag hotfix
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bumpver

      - name: Bump version
        run: |
          git config --global user.name 'aicsgithub'
          git config --global user.email 'aicsgithub@alleninstitute.org'
          python bumpver_handler.py hotfix

      - name: Commit and push
        run: |
          git add -u
          git commit -m "hotfix"
          git push origin ${{ inputs.branch }}

      - name: Create and push tag
        run: |
          python tag_with_current_version.py
          git push origin --tags
